### ISSUE TITLE
这个怎么使用？

### ISSUE THREAD

**Issue by Coding-Journey-Studio** [thelastleft-back/taobao-tianmao-auto-buy#1]
这个怎么用呢。
安装了selenium后报错
Traceback (most recent call last):
  File "D:\Python\Python37\lib\site-packages\selenium\webdriver\common\service.p
y", line 76, in start
    stdin=PIPE)
  File "D:\Python\Python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "D:\Python\Python37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tmall.py", line 16, in <module>
    driver = webdriver.Chrome()
  File "D:\Python\Python37\lib\site-packages\selenium\webdriver\chrome\webdriver
.py", line 73, in __init__
    self.service.start()
  File "D:\Python\Python37\lib\site-packages\selenium\webdriver\common\service.p
y", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executabl
e needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chrome
driver/home

**Comment by milanyummy** [comment]
你这个需要下载和你浏览器版本对应的chromedriver，并放入到你浏览器和python的路径下，并添加系统的环境变量。

**Comment by monologue1107** [comment]
> 你这个需要下载和你浏览器版本对应的chromedriver，并放入到你浏览器和python的路径下，并添加系统的环境变量。

是Mac的话要怎么解决呢

**Comment by TDHypocrites** [comment]
chromedriver一直在等待页面，到了时间也不会刷新，我看过了点之后，也没有任何反应，刷新之后就已经抢完了，这是为什么
